version: '3.7'
services:
  server:
    image: ${CONTAINER_REGISTRY_PREFIX:-ghcr.io/xarantolus}/mysti-arm64v8:latest
    build:
      context: ../..
      dockerfile: ${PWD}/Dockerfile
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./config.toml:/config.toml
    cap_add:
      - NET_ADMIN

  caddy:
    image: ${CONTAINER_REGISTRY_PREFIX:-ghcr.io/xarantolus}/mysti-caddy-namecheap-arm64v8:latest
    build:
      context: .
      dockerfile: ${PWD}/Dockerfile.caddy
    network_mode: host
    ports:
      - 728:728
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - .env
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
