version: '3.7'
services:
  server:
    image: ghcr.io/xarantolus/mysti:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - caddy_network

  caddy:
    image: caddy:2-alpine
    ports:
      - 728:728
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_network

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 1800

volumes:
  caddy_data:
  caddy_config:

networks:
  caddy_network:
    driver: bridge
