version: '3.7'
services:
  server:
    image: ${CONTAINER_REGISTRY_PREFIX:-ghcr.io/xarantolus}/philipp/mysti:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - caddy_network
    restart: unless-stopped

  caddy:
    image: ${CONTAINER_REGISTRY_PREFIX:-ghcr.io/xarantolus}/mysti-caddy:latest
    build:
      context: .
      dockerfile: Dockerfile.caddy
    ports:
      - 728:728
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_network
    env_file:
      - .env
    restart: unless-stopped


volumes:
  caddy_data:
  caddy_config:

networks:
  caddy_network:
    driver: bridge
