# Debug configuration file
server_host = "ws://localhost:8089"
token = "debug-token"

[[actions]]
name = "Shutdown"
linux = "shutdown -h now"
windows = "shutdown /s /f /t 0"

[[actions]]
name = "Logoff"
windows = "rundll32.exe user32.dll,LockWorkStation"
linux = "loginctl terminate-user philipp"

[[actions]]
name = "Reboot"
linux = "shutdown -r now"
windows = "shutdown /r /f /t 0"

