# Debug configuration file
server_host = "ws://localhost:8089"
token = "debug-token"

[[action]]
name = "Shutdown"
linux = "shutdown -h now"
windows = "shutdown /s /f /t 0"

[[action]]
name = "Logoff"
windows = "rundll32.exe user32.dll,LockWorkStation"
linux = "loginctl terminate-user philipp"

[[action]]
name = "Reboot"
linux = "shutdown -r now"
windows = "shutdown /r /f /t 0"

[[action]]
name = "Test"
linux = 'sh -c "echo $(date) $1 >> /home/philipp/Misc/test.txt"'
