[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.76"
common = { path = "../common" }
url = "2.5.0"


[[bin]]
name = "mysti"
path = "src/main.rs"
